#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-install-plugin
Version  : 2.5.2
Release  : 1
URL      : https://github.com/apache/maven-install-plugin/archive/maven-install-plugin-2.5.2.tar.gz
Source0  : https://github.com/apache/maven-install-plugin/archive/maven-install-plugin-2.5.2.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
No detailed description available

%prep

%build

%install

%files
%defattr(-,root,root,-)
