#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-install-plugin
Version  : 2.5.2
Release  : 4
URL      : https://github.com/apache/maven-install-plugin/archive/maven-install-plugin-2.5.2.tar.gz
Source0  : https://github.com/apache/maven-install-plugin/archive/maven-install-plugin-2.5.2.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
Source3  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.jar
Source4  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-install-plugin-data = %{version}-%{release}
Requires: mvn-maven-install-plugin-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
No detailed description available

%package data
Summary: data components for the mvn-maven-install-plugin package.
Group: Data

%description data
data components for the mvn-maven-install-plugin package.


%package license
Summary: license components for the mvn-maven-install-plugin package.
Group: Default

%description license
license components for the mvn-maven-install-plugin package.


%prep
%setup -q -n maven-install-plugin-maven-install-plugin-2.5.2

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-maven-install-plugin
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-maven-install-plugin/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-maven-install-plugin/NOTICE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.5.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.5.2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.jar
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.jar
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-maven-install-plugin/LICENSE
/usr/share/package-licenses/mvn-maven-install-plugin/NOTICE
